# Generated by Django 5.1.4 on 2024-12-14 02:28

import django.db.models.deletion
import dynamic_filenames
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comment', '0002_initial'),
        ('quiblet', '0002_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuibModel',
            fields=[
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True, verbose_name='create at'),
                ),
                ('is_public', models.BooleanField(default=True, verbose_name='is public')),
                (
                    'id',
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet='abcdefghijklmnopqrstuvwxyz0123456789',
                        editable=False,
                        length=7,
                        max_length=7,
                        prefix='',
                        primary_key=True,
                        serialize=False,
                        verbose_name='id',
                    ),
                ),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                (
                    'slug',
                    models.SlugField(
                        blank=True, editable=False, max_length=25, verbose_name='slug'
                    ),
                ),
                ('content', models.TextField(verbose_name='content')),
                (
                    'cover',
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=dynamic_filenames.FilePattern(
                            filename_pattern='cover/{uuid:s}{ext}'
                        ),
                        verbose_name='cover',
                    ),
                ),
                (
                    'comments',
                    models.ManyToManyField(
                        blank=True,
                        related_name='comments',
                        to='comment.comment',
                        verbose_name='comments',
                    ),
                ),
                (
                    'downvotes',
                    models.ManyToManyField(
                        blank=True,
                        related_name='downvoted_quibs',
                        to='user.profile',
                        verbose_name='downvotes',
                    ),
                ),
                (
                    'quibber',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='quibs',
                        to='user.profile',
                        verbose_name='quibber',
                    ),
                ),
                (
                    'quiblet',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='quibs',
                        to='quiblet.quibletmodel',
                        verbose_name='quiblet',
                    ),
                ),
                (
                    'upvotes',
                    models.ManyToManyField(
                        blank=True,
                        related_name='upvoted_quibs',
                        to='user.profile',
                        verbose_name='upvotes',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Quib',
                'verbose_name_plural': 'Quibs',
                'ordering': ['-created_at'],
            },
        ),
    ]
