# Generated by Django 5.1.4 on 2024-12-11 02:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quib', '0001_initial'),
        ('quiblet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quib',
            name='dislikes',
            field=models.ManyToManyField(
                blank=True,
                related_name='disliked_quibs',
                to=settings.AUTH_USER_MODEL,
                verbose_name='dislikes',
            ),
        ),
        migrations.AddField(
            model_name='quib',
            name='likes',
            field=models.ManyToManyField(
                blank=True,
                related_name='liked_quibs',
                to=settings.AUTH_USER_MODEL,
                verbose_name='likes',
            ),
        ),
        migrations.AddField(
            model_name='quib',
            name='quibber',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='quibs',
                to=settings.AUTH_USER_MODEL,
                verbose_name='quibber',
            ),
        ),
        migrations.AddField(
            model_name='quib',
            name='quiblet',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='quibs',
                to='quiblet.quiblet',
                verbose_name='quiblet',
            ),
        ),
    ]
