# Generated by Django 5.1.4 on 2024-12-17 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quib', '0001_initial'),
        ('quiblet', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quibmodel',
            name='downvotes',
            field=models.ManyToManyField(
                blank=True,
                related_name='downvoted_quibs',
                to='user.profilemodel',
                verbose_name='downvotes',
            ),
        ),
        migrations.AddField(
            model_name='quibmodel',
            name='quibber',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='quibs',
                to='user.profilemodel',
                verbose_name='quibber',
            ),
        ),
        migrations.AddField(
            model_name='quibmodel',
            name='quiblet',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='quibs',
                to='quiblet.quibletmodel',
                verbose_name='quiblet',
            ),
        ),
        migrations.AddField(
            model_name='quibmodel',
            name='upvotes',
            field=models.ManyToManyField(
                blank=True,
                related_name='upvoted_quibs',
                to='user.profilemodel',
                verbose_name='upvotes',
            ),
        ),
    ]
