# Generated by Django 5.1.4 on 2024-12-14 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quib', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quibmodel',
            name='comments',
        ),
    ]
