# Generated by Django 5.1.4 on 2024-12-18 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quib', '0003_rename_quibmodel_quib'),
    ]

    operations = [
        migrations.AddField(
            model_name='quib',
            name='highlighted',
            field=models.BooleanField(default=False, verbose_name='highlighted'),
        ),
    ]
