# Generated by Django 5.1.4 on 2024-12-16 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quib', '0004_quibmodel_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quibmodel',
            name='content',
            field=models.TextField(blank=True, verbose_name='content'),
        ),
    ]
