# Generated by Django 5.1.4 on 2024-12-25 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quib', '0004_quib_highlighted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quib',
            name='slug',
            field=models.SlugField(blank=True, max_length=25, verbose_name='slug'),
        ),
    ]
