# Generated by Django 5.1.4 on 2024-12-13 11:43

import django.contrib.postgres.indexes
import django.db.models.deletion
import django_ltree.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_alter_profile_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('path', django_ltree.fields.PathField(unique=True)),
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True, verbose_name='create at'),
                ),
                ('content', models.TextField(verbose_name='content')),
                (
                    'downvotes',
                    models.ManyToManyField(
                        blank=True,
                        related_name='downvotes',
                        to='user.profile',
                        verbose_name='downvotes',
                    ),
                ),
                (
                    'quibbler',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='user.profile',
                        verbose_name='quibbler',
                    ),
                ),
                (
                    'upvotes',
                    models.ManyToManyField(
                        blank=True,
                        related_name='upvotes',
                        to='user.profile',
                        verbose_name='upvotes',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'indexes': [
                    django.contrib.postgres.indexes.GistIndex(
                        fields=['path'], name='comment_com_path_d1388c_gist'
                    )
                ],
            },
        ),
    ]
