# Generated by Django 5.1.4 on 2024-12-13 12:02

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comment', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='downvotes',
            field=models.ManyToManyField(
                blank=True,
                related_name='downvotes',
                to='user.profile',
                verbose_name='downvotes',
            ),
        ),
        migrations.AddField(
            model_name='comment',
            name='quibbler',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='user.profile',
                verbose_name='quibbler',
            ),
        ),
        migrations.AddField(
            model_name='comment',
            name='upvotes',
            field=models.ManyToManyField(
                blank=True,
                related_name='upvotes',
                to='user.profile',
                verbose_name='upvotes',
            ),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=django.contrib.postgres.indexes.GistIndex(
                fields=['path'], name='comment_com_path_d1388c_gist'
            ),
        ),
    ]
