# Generated by Django 5.1.4 on 2024-12-17 06:02

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comment', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='downvotes',
            field=models.ManyToManyField(
                blank=True,
                related_name='downvoted_comments',
                to='user.profilemodel',
                verbose_name='downvotes',
            ),
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='quibbler',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='user.profilemodel',
                verbose_name='quibbler',
            ),
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='upvotes',
            field=models.ManyToManyField(
                blank=True,
                related_name='upvoted_comments',
                to='user.profilemodel',
                verbose_name='upvotes',
            ),
        ),
        migrations.AddIndex(
            model_name='commentmodel',
            index=django.contrib.postgres.indexes.GistIndex(
                fields=['path'], name='comment_com_path_d124df_gist'
            ),
        ),
    ]
