# Generated by Django 5.1.4 on 2024-12-17 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_initial'),
        ('quib', '0002_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommentModel',
            new_name='Comment',
        ),
        migrations.RenameIndex(
            model_name='comment',
            new_name='comment_com_path_d1388c_gist',
            old_name='comment_com_path_d124df_gist',
        ),
    ]
