# Generated by Django 5.1.4 on 2024-12-14 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_commentmodel_deleted_alter_commentmodel_quibbler'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='downvotes',
            field=models.ManyToManyField(
                blank=True,
                related_name='downvoted_comments',
                to='user.profilemodel',
                verbose_name='downvotes',
            ),
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='upvotes',
            field=models.ManyToManyField(
                blank=True,
                related_name='upvoted_comments',
                to='user.profilemodel',
                verbose_name='upvotes',
            ),
        ),
    ]
