# Generated by Django 5.1.6 on 2025-02-16 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_remove_community_is_public_community_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='type',
            field=models.CharField(
                choices=[
                    ('PUBLIC', 'Public'),
                    ('RESTRICTED', 'Restricted'),
                    ('PRIVATE', 'Private'),
                ],
                default='PUBLIC',
                verbose_name='Type',
            ),
        ),
    ]
