# Generated by Django 5.1.6 on 2025-02-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0008_remove_community_topics_topic_community_topics'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ('display_name',)},
        ),
        migrations.AlterField(
            model_name='topic',
            name='icon',
            field=models.CharField(max_length=10, verbose_name='Icon'),
        ),
    ]
