# Generated by Django 5.1.3 on 2024-12-01 17:12

import dynamic_filenames
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiblet',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True, verbose_name='create at'),
                ),
                (
                    'avatar',
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=dynamic_filenames.FilePattern(
                            filename_pattern='avatar/{uuid:s}{ext}'
                        ),
                        verbose_name='avatar',
                    ),
                ),
                ('name', models.CharField(max_length=25, unique=True, verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
                (
                    'cover',
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=dynamic_filenames.FilePattern(
                            filename_pattern='cover/{uuid:s}{ext}'
                        ),
                        verbose_name='cover',
                    ),
                ),
                ('is_public', models.BooleanField(default=True, verbose_name='is public')),
                (
                    'members',
                    models.ManyToManyField(
                        blank=True,
                        related_name='quiblets',
                        to='user.profile',
                        verbose_name='members',
                    ),
                ),
                (
                    'rangers',
                    models.ManyToManyField(
                        blank=True,
                        related_name='ranged_quiblets',
                        to='user.profile',
                        verbose_name='rangers',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Quiblet',
                'verbose_name_plural': 'Quiblets',
                'ordering': ['-created_at'],
            },
        ),
    ]
