# Generated by Django 5.1.3 on 2024-12-01 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiblet', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiblet',
            name='members',
            field=models.ManyToManyField(
                blank=True,
                related_name='joined_quiblets',
                to='user.profile',
                verbose_name='members',
            ),
        ),
    ]
