# Generated by Django 5.1.4 on 2024-12-14 02:43

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quiblet', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quibletmodel',
            name='members',
            field=models.ManyToManyField(
                blank=True,
                related_name='joined_quiblets',
                to='user.profilemodel',
                verbose_name='members',
            ),
        ),
        migrations.AddField(
            model_name='quibletmodel',
            name='rangers',
            field=models.ManyToManyField(
                blank=True,
                related_name='ranged_quiblets',
                to='user.profilemodel',
                verbose_name='rangers',
            ),
        ),
        migrations.AddConstraint(
            model_name='quibletmodel',
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower('name'),
                name='unique_quiblet_name_case_insensitive',
            ),
        ),
    ]
