# Generated by Django 5.1.4 on 2024-12-11 02:49

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quiblet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quiblet',
            name='members',
            field=models.ManyToManyField(
                blank=True,
                related_name='joined_quiblets',
                to=settings.AUTH_USER_MODEL,
                verbose_name='members',
            ),
        ),
        migrations.AddField(
            model_name='quiblet',
            name='rangers',
            field=models.ManyToManyField(
                blank=True,
                related_name='ranged_quiblets',
                to=settings.AUTH_USER_MODEL,
                verbose_name='rangers',
            ),
        ),
        migrations.AddConstraint(
            model_name='quiblet',
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower('name'),
                name='unique_quiblet_name_case_insensitive',
            ),
        ),
    ]
