# Generated by Django 5.1.4 on 2024-12-11 05:30

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quiblet', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quib',
            name='dislikes',
            field=models.ManyToManyField(
                blank=True,
                related_name='disliked_quibs',
                to='user.profile',
                verbose_name='dislikes',
            ),
        ),
        migrations.AddField(
            model_name='quib',
            name='likes',
            field=models.ManyToManyField(
                blank=True,
                related_name='liked_quibs',
                to='user.profile',
                verbose_name='likes',
            ),
        ),
        migrations.AddField(
            model_name='quib',
            name='quibber',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='quibs',
                to='user.profile',
                verbose_name='quibber',
            ),
        ),
        migrations.AddField(
            model_name='quiblet',
            name='members',
            field=models.ManyToManyField(
                blank=True,
                related_name='joined_quiblets',
                to='user.profile',
                verbose_name='members',
            ),
        ),
        migrations.AddField(
            model_name='quiblet',
            name='rangers',
            field=models.ManyToManyField(
                blank=True,
                related_name='ranged_quiblets',
                to='user.profile',
                verbose_name='rangers',
            ),
        ),
        migrations.AddField(
            model_name='quib',
            name='quiblet',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='quibs',
                to='quiblet.quiblet',
                verbose_name='quiblet',
            ),
        ),
        migrations.AddConstraint(
            model_name='quiblet',
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower('name'),
                name='unique_quiblet_name_case_insensitive',
            ),
        ),
    ]
