# Generated by Django 5.1.4 on 2024-12-17 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quib', '0003_rename_quibmodel_quib'),
        ('quiblet', '0002_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuibletModel',
            new_name='Quiblet',
        ),
    ]
