# Generated by Django 5.1.3 on 2024-12-02 01:47

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiblet', '0002_alter_quiblet_members'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='quiblet',
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower('name'),
                name='unique_quiblet_name_case_insensitive',
            ),
        ),
    ]
