# Generated by Django 5.1.4 on 2024-12-16 11:57

import dynamic_filenames
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiblet', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quibletmodel',
            name='cover',
        ),
        migrations.AddField(
            model_name='quibletmodel',
            name='banner',
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=dynamic_filenames.FilePattern(
                    filename_pattern='banner/{uuid:s}{ext}'
                ),
                verbose_name='banner',
            ),
        ),
        migrations.AddField(
            model_name='quibletmodel',
            name='title',
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name='title'
            ),
        ),
        migrations.AlterField(
            model_name='quibletmodel',
            name='name',
            field=models.CharField(
                error_messages={'unique': 'Quiblet with this name already exists.'},
                max_length=25,
                unique=True,
                verbose_name='name',
            ),
        ),
    ]
