# Generated by Django 5.1.3 on 2024-12-07 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiblet', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quib',
        ),
    ]
