# Generated by Django 5.1.4 on 2024-12-14 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quib', '0001_initial'),
        ('quiblet', '0002_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quiblet',
            new_name='QuibletModel',
        ),
        migrations.DeleteModel(
            name='Quib',
        ),
    ]
