# Generated by Django 5.1.4 on 2024-12-13 02:45

import dynamic_filenames
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiblet', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quib',
            name='cover',
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=dynamic_filenames.FilePattern(
                    filename_pattern='cover/{uuid:s}{ext}'
                ),
                verbose_name='cover',
            ),
        ),
    ]
