# Generated by Django 5.1.3 on 2024-12-02 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiblet', '0003_quiblet_unique_quiblet_name_case_insensitive'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quib',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True, verbose_name='create at'),
                ),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('slug', models.SlugField(max_length=25, verbose_name='slug')),
                ('content', models.TextField(verbose_name='content')),
                (
                    'dislikes',
                    models.ManyToManyField(
                        blank=True,
                        related_name='disliked_quibs',
                        to='user.profile',
                        verbose_name='dislikes',
                    ),
                ),
                (
                    'likes',
                    models.ManyToManyField(
                        blank=True,
                        related_name='liked_quibs',
                        to='user.profile',
                        verbose_name='likes',
                    ),
                ),
                (
                    'quibbler',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='quibbled_quibs',
                        to='user.profile',
                        verbose_name='quibbler',
                    ),
                ),
                (
                    'quiblet',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='quibs',
                        to='quiblet.quiblet',
                        verbose_name='quibs',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Quib',
                'verbose_name_plural': 'Quibs',
            },
        ),
    ]
