# Generated by Django 5.1.4 on 2024-12-17 02:40

import functools

from django.db import migrations, models

import common.mixins.model_mixins


class Migration(migrations.Migration):

    dependencies = [
        ('quiblet', '0003_remove_quibletmodel_cover_quibletmodel_banner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quibletmodel',
            name='color',
            field=models.CharField(
                choices=[
                    ('primary', 'primary'),
                    ('secondary', 'secondary'),
                    ('accent', 'accent'),
                    ('neutral', 'neutral'),
                    ('info', 'info'),
                    ('success', 'success'),
                    ('warning', 'warning'),
                    ('error', 'error'),
                ],
                default=functools.partial(
                    common.mixins.model_mixins.get_random_color,
                    *(
                        [
                            ('primary', 'primary'),
                            ('secondary', 'secondary'),
                            ('accent', 'accent'),
                            ('neutral', 'neutral'),
                            ('info', 'info'),
                            ('success', 'success'),
                            ('warning', 'warning'),
                            ('error', 'error'),
                        ],
                    ),
                    **{},
                ),
                max_length=25,
                verbose_name='color',
            ),
        ),
    ]
