# Generated by Django 5.1.4 on 2024-12-13 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
        ('quiblet', '0003_quib_cover'),
        ('user', '0003_alter_profile_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quib',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='quib',
            name='likes',
        ),
        migrations.AddField(
            model_name='quib',
            name='comments',
            field=models.ManyToManyField(
                blank=True,
                related_name='comments',
                to='comment.comment',
                verbose_name='comments',
            ),
        ),
        migrations.AddField(
            model_name='quib',
            name='downvotes',
            field=models.ManyToManyField(
                blank=True,
                related_name='downvoted_quibs',
                to='user.profile',
                verbose_name='downvotes',
            ),
        ),
        migrations.AddField(
            model_name='quib',
            name='upvotes',
            field=models.ManyToManyField(
                blank=True,
                related_name='upvoted_quibs',
                to='user.profile',
                verbose_name='upvotes',
            ),
        ),
    ]
