# Generated by Django 5.1.3 on 2024-12-02 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiblet', '0005_alter_quib_quibbler_alter_quib_quiblet'),
    ]

    operations = [
        migrations.AddField(
            model_name='quib',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='quib',
            name='quiblet',
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='quibs',
                to='quiblet.quiblet',
                verbose_name='quiblet',
            ),
        ),
    ]
