# Generated by Django 5.1.3 on 2024-12-02 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiblet', '0006_quib_is_draft_alter_quib_quiblet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quib',
            name='is_draft',
        ),
        migrations.AddField(
            model_name='quib',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
