# Generated by Django 5.1.3 on 2024-12-04 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiblet', '0009_remove_quib_quibbler_quib_quibber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quib',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='is public'),
        ),
    ]
