# Generated by Django 5.1.3 on 2024-12-04 15:39

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiblet', '0010_alter_quib_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quib',
            name='id',
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet=None,
                length=22,
                max_length=16,
                prefix='',
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name='quiblet',
            name='id',
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet=None,
                length=22,
                max_length=16,
                prefix='',
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
