# Generated by Django 5.1.3 on 2024-12-04 15:48

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiblet', '0012_alter_quib_id_alter_quiblet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quib',
            name='id',
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet='abcdefghijklmnopqrstuvwxyz0123456789',
                length=6,
                max_length=6,
                prefix='',
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name='quiblet',
            name='id',
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet='abcdefghijklmnopqrstuvwxyz0123456789',
                length=6,
                max_length=6,
                prefix='',
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
