# Generated by Django 5.1.3 on 2024-12-04 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiblet', '0014_alter_quib_id_alter_quiblet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quib',
            name='slug',
            field=models.SlugField(max_length=25, verbose_name='slug'),
        ),
    ]
