# Generated by Django 5.1.3 on 2024-12-04 16:03

import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiblet', '0015_alter_quib_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quib',
            name='id',
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet='abcdefghijklmnopqrstuvwxyz0123456789',
                length=7,
                max_length=7,
                prefix='',
                primary_key=True,
                serialize=False,
                verbose_name='id',
            ),
        ),
        migrations.AlterField(
            model_name='quib',
            name='slug',
            field=models.SlugField(
                blank=True, editable=False, max_length=25, verbose_name='slug'
            ),
        ),
        migrations.AlterField(
            model_name='quiblet',
            name='id',
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet='abcdefghijklmnopqrstuvwxyz0123456789',
                length=7,
                max_length=7,
                prefix='',
                primary_key=True,
                serialize=False,
                verbose_name='id',
            ),
        ),
    ]
