# Generated by Django 5.1.3 on 2024-12-04 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiblet', '0017_alter_quib_id_alter_quiblet_id'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quib',
            name='quibber',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='quibs',
                to='user.profile',
                verbose_name='quibber',
            ),
        ),
        migrations.AlterField(
            model_name='quib',
            name='quiblet',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='quibs',
                to='quiblet.quiblet',
                verbose_name='quiblet',
            ),
        ),
    ]
