name: Feature Request
description: Suggest a new feature or improvement for Quibble
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature! Please fill out the details below to help us understand your idea.

  - type: textarea
    id: feature-description
    attributes:
      label: Describe the feature
      description: What would you like to see in Quibble? Explain your idea as clearly as possible.
      placeholder: Describe the feature or improvement you'd like to see
    validations:
      required: true

  - type: dropdown
    id: feature-priority
    attributes:
      label: How important is this feature?
      options:
        - Low priority
        - Medium priority
        - High priority

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context or examples
      description: Include any other relevant information, links, or screenshots that could help explain the feature.
      placeholder: Add extra details here
