# Generated by Django 5.1.4 on 2025-01-17 11:45

import django.db.models.deletion
import dynamic_filenames
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_alter_comment_commenter_alter_comment_created_at_and_more'),
        ('community', '0004_alter_community_avatar_alter_community_banner_and_more'),
        ('post', '0002_initial'),
        ('user', '0002_alter_profile_avatar_alter_profile_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comments',
            field=models.ManyToManyField(
                blank=True,
                related_name='comments',
                to='comment.comment',
                verbose_name='Comments',
            ),
        ),
        migrations.AlterField(
            model_name='post',
            name='community',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='posts',
                to='community.community',
                verbose_name='Community',
            ),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=dynamic_filenames.FilePattern(
                    filename_pattern='cover/{uuid:s}{ext}'
                ),
                verbose_name='Cover',
            ),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Create at'),
        ),
        migrations.AlterField(
            model_name='post',
            name='downvotes',
            field=models.ManyToManyField(
                blank=True,
                related_name='downvoted_posts',
                to='user.profile',
                verbose_name='Downvotes',
            ),
        ),
        migrations.AlterField(
            model_name='post',
            name='highlighted',
            field=models.BooleanField(default=False, verbose_name='Highlighted'),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet='abcdefghijklmnopqrstuvwxyz0123456789',
                editable=False,
                length=7,
                max_length=7,
                prefix='',
                primary_key=True,
                serialize=False,
                verbose_name='Id',
            ),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Is public'),
        ),
        migrations.AlterField(
            model_name='post',
            name='poster',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='posts',
                to='user.profile',
                verbose_name='Poster',
            ),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=25, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='post',
            name='upvotes',
            field=models.ManyToManyField(
                blank=True,
                related_name='upvoted_posts',
                to='user.profile',
                verbose_name='Upvotes',
            ),
        ),
    ]
