# Generated by Django 5.1.6 on 2025-02-16 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_post_comments_alter_post_community_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_public',
        ),
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.CharField(
                choices=[
                    ('PUBLIC', 'Public'),
                    ('RESTRICTED', 'Restricted'),
                    ('PRIVATE', 'Private'),
                ],
                default='PUBLIC',
                verbose_name='Type',
            ),
        ),
    ]
