# Generated by Django 5.1.3 on 2024-11-29 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_user_created_at_user_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='color',
            field=models.CharField(
                blank=True,
                choices=[
                    ('primary', 'primary'),
                    ('secondary', 'secondary'),
                    ('accent', 'accent'),
                    ('neutral', 'neutral'),
                    ('info', 'info'),
                    ('success', 'success'),
                    ('warning', 'warning'),
                    ('error', 'error'),
                ],
                max_length=25,
                null=True,
            ),
        ),
    ]
