# Generated by Django 5.1.3 on 2024-11-29 16:45

import django_core.shared.mixins.models
import functools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_user_created_at_user_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='color',
            field=models.CharField(
                choices=[
                    ('primary', 'primary'),
                    ('secondary', 'secondary'),
                    ('accent', 'accent'),
                    ('neutral', 'neutral'),
                    ('info', 'info'),
                    ('success', 'success'),
                    ('warning', 'warning'),
                    ('error', 'error'),
                ],
                default=functools.partial(
                    django_core.shared.mixins.models.get_random_color,
                    *(
                        [
                            ('primary', 'primary'),
                            ('secondary', 'secondary'),
                            ('accent', 'accent'),
                            ('neutral', 'neutral'),
                            ('info', 'info'),
                            ('success', 'success'),
                            ('warning', 'warning'),
                            ('error', 'error'),
                        ],
                    ),
                    **{},
                ),
                max_length=25,
            ),
        ),
    ]
