# Generated by Django 5.1.3 on 2024-11-29 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_profile_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='color_content',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
