# Generated by Django 5.1.4 on 2024-12-14 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_rename_comment_commentmodel_and_more'),
        ('quib', '0001_initial'),
        ('quiblet', '0003_rename_quiblet_quibletmodel_delete_quib'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='ProfileModel',
        ),
    ]
