# Generated by Django 5.1.4 on 2025-01-17 11:45

import django.db.models.deletion
import dynamic_filenames
from django.conf import settings
from django.db import migrations, models

import apps.user.validators


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=dynamic_filenames.FilePattern(filename_pattern='avatar/{uuid:s}{ext}'),
                verbose_name='Avatar',
            ),
        ),
        migrations.AlterField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Create at'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name='First name'
            ),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='profiles',
                to=settings.AUTH_USER_MODEL,
                verbose_name='User',
            ),
        ),
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(
                error_messages={'unique': 'A profile with that username already exists.'},
                help_text='Required. 25 characters or fewer. Letters, digits and ./_ only.',
                max_length=25,
                unique=True,
                validators=[apps.user.validators.UsernameValidator()],
                verbose_name='Username',
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date joined'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(
                default=True,
                help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.',
                verbose_name='Active',
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(
                default=False,
                help_text='Designates whether the user can log into this admin site.',
                verbose_name='Staff status',
            ),
        ),
    ]
