# Generated by Django 5.1.4 on 2024-12-17 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_rename_commentmodel_comment_and_more'),
        ('quib', '0003_rename_quibmodel_quib'),
        ('quiblet', '0003_rename_quibletmodel_quiblet'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfileModel',
            new_name='Profile',
        ),
    ]
