# Generated by Django 5.1.3 on 2024-12-06 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={
                'ordering': ['-created_at'],
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={
                'ordering': ['-date_joined'],
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
    ]
