# Generated by Django 5.1.4 on 2024-12-11 15:47

from django.db import migrations, models

import apps.user.validators


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_profile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(
                error_messages={'unique': 'A profile with that username already exists.'},
                help_text='Required. 25 characters or fewer. Letters, digits and ./_ only.',
                max_length=25,
                unique=True,
                validators=[apps.user.validators.UsernameValidator()],
                verbose_name='username',
            ),
        ),
    ]
