# Generated by Django 5.1.5 on 2025-01-31 10:54

import dynamic_filenames
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_profile_avatar_alter_profile_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='banner',
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=dynamic_filenames.FilePattern(filename_pattern='banner/{uuid:s}{ext}'),
                verbose_name='Banner',
            ),
        ),
    ]
