name: Backend

on:
  push:
    branches:
      - '*'
    paths:
      - 'backend/**'
  pull_request:
    branches:
      - '*'
    paths:
      - 'backend/**'

jobs:
  lint:
    defaults:
      run:
        working-directory: ./backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Python, Poetry and Dependencies
        uses: packetcoders/action-setup-cache-python-poetry@main
        with:
          python-version: 3.12
          poetry-version: 1.8.4
          install-args: --directory=./backend

      - name: Run isort and flake8
        run: poetry run poe lint
