name: Frontend

on:
  push:
    branches:
      - '*'
    paths:
      - 'frontend/**'
  pull_request:
    branches:
      - '*'
    paths:
      - 'frontend/**'

jobs:
  lint:
    defaults:
      run:
        working-directory: ./frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache-dependency-path: ./frontend/package-lock.json
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run eslint
        run: npm run lint
