name: Say thanks for the contributors

on:
  pull_request_target:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-24.04-arm
    permissions:
      issues: write
      pull-requests: write
      contents: write
    steps:
      - name: Add thankyou note
        uses: actions/github-script@v7
        with:
          script: |
            const thankyou_note = 'Your contribution helps shape the future of Quibble! :rocket: Thank you for taking the time to improve the platform and make communities more engaging. We appreciate your efforts and look forward to more of your innovations. Your impact is invaluable! :raised_hands:';
            const options = {
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
            };

            const { data : { assignees, user } } = await github.rest.issues.get(options);

            const tagged_users = [...new Set(
              assignees.map(u => "@"+u.login).concat("@"+user.login)  
            )].join(" ")

            await github.rest.issues.createComment({ 
              ...options, 
              body: `${tagged_users} ${thankyou_note}` 
            });
