name: Say thanks for the contributors

on:
  pull_request_target:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
    steps:
      - name: Add thankyou note
        uses: actions/github-script@v7
        with:
          script: |
            const thankyou_note = 'Your contribution makes Quibble a better place for open discussions and thriving communities! :sparkles: Thank you for helping shape the platform with your efforts. We appreciate your time and dedication—keep building, keep quibbling! :speech_balloon: Your impact matters! :raised_hands:';
            const options = {
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
            };

            const { data : { assignees, user } } = await github.rest.issues.get(options);

            const tagged_users = [...new Set(
              assignees.map(u => "@"+u.login).concat("@"+user.login)  
            )].join(" ")

            await github.rest.issues.createComment({ 
              ...options, 
              body: `${tagged_users} ${thankyou_note}` 
            });
